# Website Info
site_name: LaVague
site_url: https://docs.lavague.ai/en/latest/
site_author: Mithril Security

# Repository
repo_name: lavague-ai/LaVague
repo_url: https://github.com/lavague-ai/LaVague

# Configuration
theme:
  name: material
  custom_dir: docs/material_theme_customization
  features:
    - navigation.instant
    - search.highlight
    - content.tabs.link
    - navigation.sections
    - navigation.indexes
    - navigation.expand
    
  logo: assets/logo.png
  favicon: assets/logo.png
  theme:
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  icon:
    admonition:
      note: material/pencil-circle
      abstract: material/list-box-outline
      info: material/information-outline
      tip: material/fire
      success: material/check
      question: material/help-circle
      warning: material/alert
      failure: material/window-close
      danger: material/lightning-bolt-circle
      bug: material/shield-bug
      example: material/test-tube
      quote: material/format-quote-close

#Plugins
plugins:
  - search
  - mkdocs-jupyter

# Customization
extra:
  homepage: https://mithrilsecurity.io
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.com/invite/TxEHagpWd4
    - icon: fontawesome/brands/github
      link: https://github.com/mithril-security/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/mithril-security-company/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/mithrilsecurity

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - "https://code.jquery.com/jquery-3.3.1.min.js"

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.critic


# Documentation tree
nav:
- 🏠 Home: 'index.md'

- 🚀 Getting Started: 
  - Installation: 'docs/get-started/setting-up-la-vague.md'
  - Quick tour: 'docs/get-started/quick-tour.ipynb'
  - Alpha VSCode extenstion: 'docs/get-started/get-started-vscode-extension.md'
  - Playwright: 'docs/get-started/playwright.md'
  - Customization: 'docs/get-started/customization.md'

- 🤝 Integrations:
  - Overview: 'docs/integrations/home.md'
  - Api:
    - Azure OpenAI: 'docs/integrations/api/azure-openai.ipynb'
    - HuggingFace: 'docs/integrations/api/hugging-face.ipynb'
    - OpenAI: 'docs/integrations/api/openai.ipynb'
    - Litellm: 'docs/integrations/api/litellm.ipynb'
  - Local:
    - DeepSeek Coder: 'docs/integrations/local/local-inference.ipynb'
  
- ⚡ Advanced:
  - Architecture: 'docs/get-started/architecture.md'
  - Telemetry: 'docs/advanced/telemetry.md'
  - Under the hood: 'docs/advanced/under-the-hood.md'

- 🤗 Contributing:
  - Contributors' guide: "docs/contributing/contributing.md"

- 🛠️ API reference:
  - API reference home: 'docs/lavague/index.html'
