openai_api:
  api_key: ${OPENAI_API_KEY}

litellm:
  model: "gpt-3.5-turbo"
  default_max_new_tokens: 512

huggingface:
  auth_token: ${HF_TOKEN}
  inference:
    mixtral:
      default_max_new_tokens: 512
      api_llm: "NousResearch/Nous-Hermes-2-Mixtral-8x7B-DPO"
      local_embed_model: "BAAI/bge-small-en-v1.5"


azure_openai:
  api_key: ${AZURE_OPENAI_KEY}
  api_version: "2023-05-15"
  azure_endpoint: ${AZURE_OPENAI_ENDPOINT}
  model: "gpt-4"
  deployment_name: ${AZURE_OPENAI_DEPLOYMENT_NAME:-gpt-4-turbo}

groq_api:
  api_key: ${GROQ_API_KEY}
  model: "mixtral-8x7b-32768" # gemma-7b-it, llama2-70b-4096

anthropic_api:
  api_key: ${ANTHROPIC_API_KEY}
  model: "claude-3-haiku-20240307" # claude-3-sonnet-20240229, claude-3-opus-20240229
